In [156]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("WildFires_DataSet.csv")
data.replace(('fire', 'no_fire'), (1, 0), inplace=True)

data.head

<bound method NDFrame.head of           NDVI           LST  BURNED_AREA  CLASS
0     0.506782  14584.272727     4.692308      0
1     0.522150  14655.833333     5.000000      0
2     0.682284  14780.000000     5.000000      1
3     0.120046  13298.500000     3.500000      0
4     0.568734  14743.000000     5.000000      0
...        ...           ...          ...    ...
1708  0.621721  14406.000000     5.000000      0
1709  0.709715  14330.400000     4.851852      0
1710  0.613000  14751.500000     3.000000      1
1711  0.614471  13611.000000     4.921053      0
1712  0.549497  14269.777778     5.000000      1

[1713 rows x 4 columns]>

In [157]:
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values
x

array([[5.06782000e-01, 1.45842727e+04, 4.69230800e+00],
       [5.22150000e-01, 1.46558333e+04, 5.00000000e+00],
       [6.82284000e-01, 1.47800000e+04, 5.00000000e+00],
       ...,
       [6.13000000e-01, 1.47515000e+04, 3.00000000e+00],
       [6.14471000e-01, 1.36110000e+04, 4.92105300e+00],
       [5.49497000e-01, 1.42697778e+04, 5.00000000e+00]])

In [158]:
from sklearn.model_selection import train_test_split, cross_val_score

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [159]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [160]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=7)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [161]:
y_pred = model.predict(x_test)

In [162]:
from sklearn.metrics import confusion_matrix, accuracy_score

confusion_matrix(y_test, y_pred)

array([[251,  19],
       [ 48,  25]], dtype=int64)

In [163]:
accuracy_score(y_test, y_pred)

0.8046647230320699

In [164]:
cross_val_score(model, x_train, y_train, cv=10)

array([0.7810219 , 0.77372263, 0.81021898, 0.78832117, 0.73722628,
       0.75912409, 0.74452555, 0.77372263, 0.79562044, 0.76642336])